title: <p align="center"> K Gohad </p>
logo: /assets/img/logo.png
description: 
  <p align="center">
  
  
  
  <br>   
  I'm working on Data Science and ML Projects
  <br>
  </p>


theme: jekyll-theme-minimal
